spring:
  jpa:
    hibernate.ddl-auto: none
  #    properties:
  #      hibernate:
  #        temp:
  #          use_jdbc_metadata_defaults: true
  datasource:
    #    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:warsaw-hospital-backend}
    #    username: ${DB_USER:postgres}
    #    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/warsaw-hospital-backend
    username: root
    password: example
  #    disable flyway for build
  flyway:
    baselineOnMigrate: true
    locations: "classpath:db/migration/common, classpath:db/migration/data"
app:
  jwt:
    secret: ${JWT_SECRET:Am@z11nGS3eEcR4tBBDcbb}
    expirationMs: 172800000 # 2 days
  generated-password-length: 12
  thread-count: 20



