#security:
#  basic:
#    enabled: false
#  management:
#    enabled: false
spring:
  jpa:
    hibernate.ddl-auto: none
  datasource:
    #    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/warsaw-hospital-backend
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5435/warsaw-hospital-backend
    username: root
    password: example
    driver-class-name: org.postgresql.Driver
  #    disable flyway for build
  flyway:
    baselineOnMigrate: true
    locations: "classpath:db/migration/common, classpath:db/migration/data"
app:
  BASE_URL: http://localhost:3000
  jwt:
    secret: ${JWT_SECRET:Am@z11nGS3eEcR4tBBDcbb}
    expirationMs: 172800000 # 2 days
  generated-password-length: 12
  thread-count: 20



