spring:
  jpa:
    hibernate.ddl-auto: none
  mail:
    username: warsaw-hospital@gmail.com
    password: bruh
    host: kedras.serveriai.lt
    port: 587
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
      transport:
        protocol: smtp
  datasource:
    url: jdbc:postgresql://localhost:5435/warsaw-hospital-backend
    username: root
    password: example
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    locations: "classpath:db/migration/common, classpath:db/migration/data, classpath:db/migration/data/dev"
app:
  BASE_URL: http://localhost:3000
  jwt:
    secret: ${JWT_SECRET:Am@z11nGS3eEcR4tBBDcbb}
    expirationMs: 172800000 # 2 days
  generated-password-length: 12
  thread-count: 20



