package com.warsaw.hospital.doctor.enums;

public enum DoctorSpecializationEnum {
  CARDIOLOGIST,
  DENTIST,
  DERMATOLOGIST,
  ENDOCRINOLOGIST,
  GASTROENTEROLOGIST,
  GYNECOLOGIST,
  NEUROLOGIST,
  OPHTHALMOLOGIST,
  OTOLARYNGOLOGIST,
  ORTHOPEDIST,
  PEDIATRICIAN,
  PSYCHIATRIST,
  RADIOLOGIST,
  SURGEON,
  UROLOGIST,
  VENEREOLOGIST,
  OTHER
}
